# These are supported funding model platforms

github: [lachlanchen]

custom: [
  "https://github.com/sponsors/lachlanchen",
  "https://lazying.art",
  "https://chat.lazying.art",
  "https://onlyideas.art"
]
